#  docker-compose.yml

services:
  gpio-controller:
    build: .
    ports:
      - "80:3000"
    volumes:
      - /sys:/sys:ro
      - /dev:/dev
      - /proc/device-tree/model:/proc/device-tree/model:ro
    devices:
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - API_ENDPOINT=${API_ENDPOINT}
      - API_URL=${API_URL}
      - COMPANY_ID=${COMPANY_ID}
      - DATABASE_URL=${DATABASE_URL}
      - DEVICE_ID=${DEVICE_ID}
      - ENVIRONMENT=${ENVIRONMENT}
      - PORT=${PORT}
      - TIME_ON_BULB=${TIME_ON_BULB}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"