#  docker-compose.yml

services:
  gpio-controller:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - /sys:/sys:ro
      - /dev:/dev
    devices:
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    environment:
      - API_URL=${API_URL}
      - API_ENDPOINT=${API_ENDPOINT}
      - DEVICE_ID=${DEVICE_ID}
      - COMPANY_ID=${COMPANY_ID}
      - DATABASE_URL=sqlite:///./data/dev.db
      - PORT=3000
      - ENVIRONMENT=production
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"