services:
  # Production service
  gpio-controller:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: gpio-prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - API_URL=${API_URL}
      - API_ENDPOINT=${API_ENDPOINT}
      - COMPANY_ID=${COMPANY_ID}
      - DEVICE_ID=${DEVICE_ID}
      - DATABASE_URL=file:./data/dev.db
    privileged: true
    volumes:
      - "/sys:/sys"
      - "/dev:/dev"
      - ./data:/app/data
    devices:
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    cap_add:
      - SYS_RAWIO
    group_add:
      - gpio
    networks:
      - gpio-network
    profiles:
      - production

  # Development service with hot reload
  gpio-controller-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gpio-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_URL=${API_URL}
      - API_ENDPOINT=${API_ENDPOINT}
      - COMPANY_ID=${COMPANY_ID}
      - DEVICE_ID=${DEVICE_ID}
      - DATABASE_URL=file:./data/dev.db
    privileged: true
    volumes:
      - .:/app
      - /app/node_modules  # Exclude node_modules from mount
      - "/sys:/sys"
      - "/dev:/dev"
      - ./data:/app/data
    devices:
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    cap_add:
      - SYS_RAWIO
    group_add:
      - gpio
    networks:
      - gpio-network
    profiles:
      - development

networks:
  gpio-network:
    driver: bridge
